version: '3.4'

services:  
 db:
  image: mcr.microsoft.com/mssql/server:2017-latest
  environment:
   - SA_PASSWORD=Pass@word
   - ACCEPT_EULA=Y
  ports:
   - "1401:1433"

 script:
  build: .
  network_mode: host
  volumes:
   - .:/usr/src/app
  #command: python main.py
  depends_on:
   - db